# frps configuration for use with frp-proxy panel
bindPort = 7000
vhostHTTPPort = 8081
subDomainHost = "example.com"

[[httpPlugins]]
name = "login"
addr = "http://127.0.0.1:5040"
path = "/api/plugin/login"
ops = ["Login"]

[[httpPlugins]]
name = "new-proxy"
addr = "http://127.0.0.1:5040"
path = "/api/plugin/new-proxy"
ops = ["NewProxy"]
